import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    content: {
        flex: 1,
        paddingTop: 22,
    },
    search: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        backgroundColor: '#d3d3d3',
        padding: 6,
        borderRadius: 20,
        width: '90%',
        borderWidth: 1,
    },
    textInput: {
        flex: 1,
        alignItems: 'center',
        padding: 0,
    },
    iconSearch: {
        marginLeft: "auto",
    },
    apartado: {
        top: 20,
        flexDirection: 'row',
        justifyContent: "space-evenly", 
    },
    div1: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div2: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div3: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div4: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25,
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div5: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div6: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div7: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div8: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div9: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div10: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div11: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div12: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div13: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div14: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
    div15: {
        alignItems: 'center',
        backgroundColor: '#d3d3d3', 
        padding: 25, 
        paddingHorizontal: 40, 
        borderRadius: 20, 
        marginTop: 20, 
        width: '100%',
        borderWidth: 1,
    },
})
export default styles;