# Generated by Django 3.2 on 2024-06-05 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200, unique=True, validators=[tasks.models.validate_number])),
                ('email', models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')])),
                ('psw', models.CharField(max_length=200, validators=[tasks.models.validate_password])),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tasks.register')),
            ],
        ),
    ]
