# Generated by Django 3.2 on 2024-06-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('register_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.register')),
                ('specialty', models.CharField(max_length=200)),
            ],
            bases=('tasks.register',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to='tasks.register')),
                ('userReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='tasks.register')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.DateTimeField()),
                ('forWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='tasks.register')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointment', to='tasks.doctors')),
            ],
        ),
    ]
