# Generated by Django 3.2 on 2024-06-08 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_appointment_doctors_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('register_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.register')),
                ('specialty', models.CharField(max_length=200)),
                ('emailClinic', models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.'), tasks.models.validate_doctor_email])),
            ],
            bases=('tasks.register',),
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointment', to='tasks.doctor'),
        ),
    ]
