# Generated by Django 3.2 on 2024-06-08 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20240608_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200, unique=True, validators=[tasks.models.validate_number])),
                ('emailClinic', models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.'), tasks.models.validate_doctor_email])),
                ('psw', models.CharField(max_length=200, validators=[tasks.models.validate_password])),
                ('specialty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to='tasks.register')),
                ('userReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='tasks.register')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.DateTimeField()),
                ('forWhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='tasks.register')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointment', to='tasks.doctor')),
            ],
        ),
    ]
