# Generated by Django 3.2 on 2024-06-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_appointments_doctor_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='emailClinic',
            new_name='email',
        ),
    ]
