# Generated by Django 3.2 on 2024-06-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_emailclinic_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='userEmisor',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='userReceptor',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
