# Generated by Django 3.2 on 2024-06-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_appointments_doctor_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='forWhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='tasks.register'),
        ),
    ]
